#!python
# encoding: utf-8

outexe = 'diff-wave'

sources = """
    diff-wave.c
"""

include_dirs = """
    ../../include
"""

def options(opt):
    opt.load('compiler_c')

def configure(conf):
    conf.load('compiler_c')
    CC_NAME = conf.env.CC_NAME
    if CC_NAME == 'msvc':
        conf.env.append_value('CFLAGS', ['/Wall', '/Zi'])
    elif CC_NAME == 'gcc':
        conf.env.append_value('CFLAGS', ['-W', '-Wall', '-std=c99', '-g', '-O0'])

def build(bld):
    bld.program(
        source      = sources,
        target      = outexe,
        includes    = include_dirs,
        use         = 'libwave',
    )
